USE [DB_SLEVEL]
GO

/****** Object:  Table [dbo].[TBL_CAMPOS_ENCUESTA]    Script Date: 7/7/2023 9:11:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_CAMPOS_ENCUESTA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ENCUESTAID] [int] NOT NULL,
	[NOMBRE] [nvarchar](100) NOT NULL,
	[TITULO] [nvarchar](100) NOT NULL,
	[ESREQUERIDO] [bit] NOT NULL,
	[TIPOCAMPO] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_CAMPOS_ENCUESTA]  WITH CHECK ADD FOREIGN KEY([ENCUESTAID])
REFERENCES [dbo].[TBL_ENCUESTAS] ([ID])
GO


